In [19]:
import pandas as pd
import numpy as np

data = pd.read_csv("../Dataset/Car Price.csv")

print("Dataset loaded successfully!")
print("Original shape:", data.shape)

data.head()

Dataset loaded successfully!
Original shape: (4340, 9)

,Brand,Model,Year,Selling_Price,KM_Driven,Fuel,Seller_Type,Transmission,Owner
0,Maruti,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [20]:
print("Duplicate rows before removal:", data.duplicated().sum())

data = data.drop_duplicates().reset_index(drop=True)

print("Duplicate rows after removal:", data.duplicated().sum())
print("New dataset shape:", data.shape)

Duplicate rows before removal: 763
Duplicate rows after removal: 0
New dataset shape: (3577, 9)

In [21]:
print("Data Types:")
print(data.dtypes)

Data Types:
Brand              str
Model              str
Year             int64
Selling_Price    int64
KM_Driven        int64
Fuel               str
Seller_Type        str
Transmission       str
Owner              str
dtype: object

In [22]:
from datetime import datetime

current_year = datetime.now().year

data["Car_Age"] = current_year - data["Year"]

data["KM_per_Year"] = (
    data["KM_Driven"] /
    data["Car_Age"].replace(0, 1)
)

print("Current Year:", current_year)
print("Feature engineering completed!")

data[
    ["Year", "KM_Driven", "Car_Age", "KM_per_Year"]
].head()

Current Year: 2026
Feature engineering completed!

   Year  KM_Driven  Car_Age   KM_per_Year
0  2007      70000       19   3684.210526
1  2007      50000       19   2631.578947
2  2012     100000       14   7142.857143
3  2017      46000        9   5111.111111
4  2014     141000       12  11750.000000

In [24]:
features = [
    "Brand",
    "Model",
    "Year",
    "KM_Driven",
    "Fuel",
    "Seller_Type",
    "Transmission",
    "Owner",
    "Car_Age",
    "KM_per_Year"
]

X = data[features]

y = data["Selling_Price"]

print("Features selected successfully!")

print("\nInput Features:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

print("\nFeature shape:", X.shape)
print("Target shape:", y.shape)

Features selected successfully!

Input Features:
['Brand', 'Model', 'Year', 'KM_Driven', 'Fuel', 'Seller_Type', 'Transmission', 'Owner', 'Car_Age', 'KM_per_Year']

Target:
Selling_Price

Feature shape: (3577, 10)
Target shape: (3577,)

In [ ]:
categorical_features = [
    "Brand",
    "Model",
    "Fuel",
    "Seller_Type",
    "Transmission",
    "Owner"
]

numerical_features = [
    "Year",
    "KM_Driven",
    "Car_Age",
    "KM_per_Year"
]

print("Categorical Features:")
print(categorical_features)

print("\nNumerical Features:")
print(numerical_features)

Categorical Features:
['Brand', 'Model', 'Fuel', 'Seller_Type', 'Transmission', 'Owner']

Numerical Features:
['Year', 'KM_Driven', 'Car_Age', 'KM_per_Year']

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

encoded_data = encoder.fit_transform(
    X[categorical_features]
)

print("One-Hot Encoding completed!")
print("Encoded shape:", encoded_data.shape)

One-Hot Encoding completed!
Encoded shape: (3577, 1535)

In [ ]:
# Convert numerical features to NumPy array
numerical_data = X[numerical_features].to_numpy()

# Combine categorical and numerical features
X_processed = np.hstack([
    encoded_data,
    numerical_data
])

print("Preprocessing completed!")
print("Final processed feature shape:", X_processed.shape)
print("Target shape:", y.shape)

Preprocessing completed!
Final processed feature shape: (3577, 1539)
Target shape: (3577,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_processed,
    y,
    test_size=0.20,
    random_state=42
)

print("Train-Test Split completed!")

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

Train-Test Split completed!
Training features: (2861, 1539)
Testing features: (716, 1539)
Training target: (2861,)
Testing target: (716,)

In [ ]:
print("FEATURE ENGINEERING SUMMARY")
print("=" * 40)

print("1. Car_Age")
print("   Formula: Current Year - Year")

print("\n2. KM_per_Year")
print("   Formula: KM_Driven / Car_Age")

print("\nEngineered Features:")
print(data[[
    "Year",
    "KM_Driven",
    "Car_Age",
    "KM_per_Year"
]].head())

FEATURE ENGINEERING SUMMARY
========================================
1. Car_Age
   Formula: Current Year - Year

2. KM_per_Year
   Formula: KM_Driven / Car_Age

Engineered Features:
   Year  KM_Driven  Car_Age   KM_per_Year
0  2007      70000       19   3684.210526
1  2007      50000       19   2631.578947
2  2012     100000       14   7142.857143
3  2017      46000        9   5111.111111
4  2014     141000       12  11750.000000

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print("ML models and evaluation metrics imported successfully!")

ML models and evaluation metrics imported successfully!

In [ ]:
from sklearn.model_selection import GridSearchCV

print("GridSearchCV imported successfully!")

GridSearchCV imported successfully!

In [ ]:
rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

print("Hyperparameter grid created!")
print("Total combinations:",
      2 * 3 * 2 * 2)

Hyperparameter grid created!
Total combinations: 24

In [ ]:
rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

print("Hyperparameter grid created!")
print("Total combinations:",
      2 * 3 * 2 * 2)

Hyperparameter grid created!
Total combinations: 24

In [ ]:
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring="r2",
    n_jobs=-1,
    verbose=1
)
print("Starting hyperparameter tuning...")
grid_search.fit(X_train, y_train)
print("Hyperparameter tuning completed!")

Starting hyperparameter tuning...
Fitting 3 folds for each of 24 candidates, totalling 72 fits
Hyperparameter tuning completed!

In [ ]:
print("BEST HYPERPARAMETERS")
print("=" * 40)

print(grid_search.best_params_)

print("\nBest Cross-Validation R²:")
print(grid_search.best_score_)

BEST HYPERPARAMETERS
========================================
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}

Best Cross-Validation R²:
0.6157224416173833

In [ ]:
best_rf = grid_search.best_estimator_

tuned_pred = best_rf.predict(X_test)

tuned_mae = mean_absolute_error(y_test, tuned_pred)
tuned_mse = mean_squared_error(y_test, tuned_pred)
tuned_rmse = np.sqrt(tuned_mse)
tuned_r2 = r2_score(y_test, tuned_pred)

print("TUNED RANDOM FOREST RESULTS")
print("=" * 40)

print("MAE :", round(tuned_mae, 2))
print("MSE :", round(tuned_mse, 2))
print("RMSE:", round(tuned_rmse, 2))
print("R²  :", round(tuned_r2, 4))

TUNED RANDOM FOREST RESULTS
========================================
MAE : 139365.82
MSE : 130411857872.77
RMSE: 361125.82
R²  : 0.5952

In [ ]:
print("RANDOM FOREST - BEFORE vs AFTER TUNING")
print("=" * 50)

print("Before Tuning")
print("R² :", 0.6936)
print("MAE:", 102623.16)

print("\nAfter Tuning")
print("R² :", round(tuned_r2, 4))
print("MAE:", round(tuned_mae, 2))

print("\nFINAL DECISION")

if tuned_r2 > 0.6936:
    print("Tuned Random Forest selected.")
else:
    print("Original Random Forest selected.")

RANDOM FOREST - BEFORE vs AFTER TUNING
==================================================
Before Tuning
R² : 0.6936
MAE: 102623.16

After Tuning
R² : 0.5952
MAE: 139365.82

FINAL DECISION
Original Random Forest selected.